### PR TITLE
Acknowledge Swissuniversities in the README file

### PR DESCRIPTION
**Pull request by borellim**
Adds an acknowledgement to swissunversities to the README file. I couldn't find a place to put the logo, let me know if you want it somewhere.

### CODE REVIEW

**Comment by yakutovicha** [comment]
Thanks @borellim. Can you also add acknowledgements to Marvel and Max. The same way as it is done for `aiida-core`. 

Concerning the images, just add `miscellaneous` folder and put them there.

**Comment by borellim** [comment]
Ok. Now I see that aiida-core also lacks an acknowledgement to swissuniversities, so I will add it there too.

I will use bullet points like this, if it's OK: https://github.com/aiidateam/aiida-quantumespresso/pull/457/files

**Comment by yakutovicha** [comment]
> Ok. Now I see that aiida-core also lacks an acknowledgement to swissuniversities, so I will add it there too.
> 
> I will use bullet points like this, if it's OK: https://github.com/aiidateam/aiida-quantumespresso/pull/457/files

that is perfect!

**Comment by borellim** [comment]
Better? I took it from aiida-core.

**Comment by yakutovicha** [comment]
> Better? I took it from aiida-core.

piece of art!

**Comment by borellim** [comment]
Really sorry, I forgot one minor thing.

**Comment by yakutovicha** [comment]
thanks @borellim

**Pull request merged**
