### PR TITLE
Move tests to the pytest framework.

### LINKED ISSUE #28: Move examples to pytest framework
Same way as it is done in the [aiida-cp2k](https://github.com/aiidateam/aiida-cp2k/pull/49)

Todos:

- [x] Make sure examples are automatically run by pytest
- [x] Rename examples from `test_` to `example_`

### LINKED ISSUE #29: Add coveralls
as the title says. To be fixed after #28

### LINKED ISSUE #31: Add coveralls, and build (travis) bandges

### PR DESCRIPTION
**Pull request by yakutovicha**
fixes #28 
fixes #29 
fixes #31

### CODE REVIEW

**Comment by yakutovicha** [comment]
@ltalirz do you have an idea why the 0907397 tests are failing?

The problem is with `example_base_binary_restart.py` If I run it without pytest, it goes fine, but under `pytest` it is hanging.

**Comment by ltalirz** [comment]
I would have to look through the code...
If you can reproduce it locally, it should be quite straightforward to figure out which part is hanging.

**Comment by yakutovicha** [comment]
> I would have to look through the code...
> If you can reproduce it locally, it should be quite straightforward to figure out which part is hanging.

Yes, locally I have the same problem. But I don't know what to look at to understand the origin of the strange behaviour.

Looks like the calculation wasn't submitted and `top` doesn't show anything strange.

What should I look at to narrow down the origin of the problem?

**Comment by yakutovicha** [comment]
I am going to merge this PR to make a release. The [issue](https://github.com/yakutovicha/aiida-raspa/issues/40) of the hanging test I will solve in a different PR.

**Pull request merged**
