### PR TITLE
Log RASPA warnings, write .cif files in RASPA-stable format

### PR DESCRIPTION
**Pull request by kjappelbaum**
@danieleongari  highlighted to me today that RASPA often has problems parsing .cifs. 

I suggest two changes/additions:
1) Log RASPA warnings so users can see that a problem occurred (e.g. this particular warning one gives rise to a warning (` THERE ARE ATOM-PAIRS WITH NO VDW INTERACTION`) . One could maybe make more specific warnings in the future (when I understand more about RASPA).
2) Write .cifs in a RASPA stable format. I know that this change is a bit against the design decision of CIfData, which claims to leave the information unchanged, but I think that it would be good to avoid any cif parsing errors with RASPA in the future.  I also added ase as requirement (any version should be fine?) as it is only a requirement in the atomic_tools extras of aiida_core. 

What do you think?

### CODE REVIEW

**Comment by kjappelbaum** [comment]
using the ase-type cif files also has the advantage that one can always use the option `RemoveAtomNumberCodeFromLabel`  (cp. Raspa manual 2..6.3)

**Comment by kjappelbaum** [comment]
As just discussed, [ase tries to parse the symmetry information](https://gitlab.com/ase/ase/blob/master/ase/io/cif.py). But a more elegant/safe option would be to just check for the atom_label column and just modify this one if it is not in the correct format. We could borrow the code from the ase parser to do this.

**Comment by yakutovicha** [comment]
Another problem that I found in the ase conversion is that it looses charges (_atom_site_charge column was gone after the conversion). I tried to convert 
[ACOLIP.cif.txt](https://github.com/yakutovicha/aiida-raspa/files/2940691/ACOLIP.cif.txt) and I got the following converted file 
[converted_ACOLIP.cif.txt](https://github.com/yakutovicha/aiida-raspa/files/2940711/converted_ACOLIP.cif.txt).

So I would definitely avoid using ASE directly.

>  But a more elegant/safe option would be to just check for the atom_label column and just modify this one if it is not in the correct format. We could borrow the code from the ase parser to do this.

Agree. Also, one could use CIfFile module, as I do in the [aiida-ddec parser](https://github.com/yakutovicha/aiida-ddec/blob/master/aiida_ddec/parsers/__init__.py.) to operate with the cif files.

**Comment by kjappelbaum** [comment]
> Agree. Also, one could use CIfFile module, as I do in the [aiida-ddec parser](https://github.com/yakutovicha/aiida-ddec/blob/master/aiida_ddec/parsers/__init__.py.) to operate with the cif files.

```
import CifFile
import re

try: 
    img0 = cf.dictionary[cf.keys()[0]]
    labels = img0.GetFullItemValue('_atom_site_label')[0]
    for label in labels: 
        if not re.match('\w+\d+', label):
            self.logger.warning('atom site label potentially in wrong format')
            break
except KeyError:
    self.logger.warning('could not find _atom_site_label')
```

We should probably check how the parser works if we have multiple lines at the beginning, I saw that you use `image_0` in the other parser, but I think that this might be not generally the case (maybe the first entry in the dictionary is better?).  For a that fixes the column I would also work in a `try` / `except KeyError` enviornment to account for cases in which the file e.g. does not contain atom symbols in a format which we expect, but for fixing i would just parse the atom symbols column and concatenate the string with the label number.

**Comment by yakutovicha** [comment]
ok, as we agreed I will close this PR. Usage of ASE is not appropriate for our purposes. Warnings parser is added together with migration to aiida-1.0

**Pull request closed without merging**
